// Package config loads and represents praetorian configuration.
//
// The configuration is written in HCL (humans) and is equally parseable as
// JSON (e.g. generated by Nix via builtins.toJSON), because hashicorp/hcl
// parses JSON natively.
//
// Schema:
//
//	alias "okinawa-tpm" {
//	  allow "borg serve" {}          # required token prefix, any trailing args
//
//	  allow "git-receive-pack" {
//	    arg { pos = 1, glob = "/srv/git/*" }
//	    num_args = 1
//	  }
//
//	  allow "rsync" {
//	    any_arg = "/srv/backup/*"           # at least one arg must match
//	    no_arg  = "/srv/backup/.secret/*"   # narrowing: no arg may match
//	  }
//	}
package config

import (
	"fmt"

	"github.com/hashicorp/hcl/v2/hclsimple"
)

// Config is the top-level praetorian configuration.
type Config struct {
	Aliases []Alias `hcl:"alias,block"`
}

// Alias maps a key alias (referenced from authorized_keys via
// `command="praetorian run <alias>"`) to a set of allow rules.
type Alias struct {
	Name  string  `hcl:"name,label"`
	Allow []Allow `hcl:"allow,block"`
}

// Allow is a single allow rule. The label (Command) is shlex-split into a
// required token prefix; the first token is the executable name and any
// remaining tokens are required leading arguments. Constraints are evaluated
// against the arguments that follow the prefix.
//
// A command is permitted if any Allow rule matches: its prefix matches and all
// of its constraints are satisfied. Default-deny otherwise.
type Allow struct {
	Command string          `hcl:"command,label"`
	Args    []ArgConstraint `hcl:"arg,block"`
	AnyArg  *string         `hcl:"any_arg"`
	NoArg   *string         `hcl:"no_arg"`
	NumArgs *int            `hcl:"num_args"`
}

// ArgConstraint requires the argument at a 1-based position to match a glob.
// Negative positions index from the end (-1 is the last argument).
type ArgConstraint struct {
	Pos  int    `hcl:"pos"`
	Glob string `hcl:"glob"`
}

// Load reads and decodes a config file. The extension selects the parser:
// `.json` is parsed as JSON, anything else as HCL.
func Load(path string) (*Config, error) {
	var cfg Config
	if err := hclsimple.DecodeFile(path, nil, &cfg); err != nil {
		return nil, fmt.Errorf("loading config %s: %w", path, err)
	}
	return &cfg, nil
}

// Lookup returns the alias with the given name, or nil if not found.
func (c *Config) Lookup(name string) *Alias {
	for i := range c.Aliases {
		if c.Aliases[i].Name == name {
			return &c.Aliases[i]
		}
	}
	return nil
}
